### ISSUE TITLE
npm install error on window 10

### ISSUE THREAD

**Issue by martinwh99** [ffxsam/ffx-meteor-react-boilerplate#2] opened 2016-02-11 08:07 UTC
seems to be   /bin/sh ./.scripts/postinstall.sh wich is linux

npm ERR! ffx-meteor-react-boilerplate@1.0.0 postinstall: `/bin/sh ./.scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffx-meteor-react-boilerplate@1.0.0 postinstall script.
npm ERR! This is most likely a problem with the ffx-meteor-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     /bin/sh ./.scripts/postinstall.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffx-meteor-react-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 10.0.10586
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd E:\dev_meteor_1.3\ffx-meteor-react-boilerplate
npm ERR! node -v v5.4.0
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\dev_meteor_1.3\ffx-meteor-react-boilerplate\npm-debug.log
npm ERR! not ok code 0

regards
Martin

**Comment by ffxsam** [comment] 2016-02-11 08:09
Duplicate of #1 - no Windows support currently, need help from a Windows dev on this.

**Closed by ffxsam** 2016-02-11 08:09 UTC
